-- Stock Logs Table for tracking all inventory transactions
-- Run this SQL in your Supabase SQL Editor to create the table

CREATE TABLE IF NOT EXISTS stock_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number TEXT NOT NULL,
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('ISSUE', 'RECEIVE', 'ADJUST', 'ADD')),
    quantity DECIMAL(10,2) NOT NULL,
    previous_stock DECIMAL(10,2) NOT NULL,
    new_stock DECIMAL(10,2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add index for faster queries
CREATE INDEX IF NOT EXISTS idx_stock_logs_part_number ON stock_logs(part_number);
CREATE INDEX IF NOT EXISTS idx_stock_logs_created_at ON stock_logs(created_at DESC);

